package fr.axllvy.insane.data

import androidx.compose.runtime.staticCompositionLocalOf
import fr.axllvy.insane.Config
import fr.axllvy.insane.logE
import fr.axllvy.insane.resources.Res
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import org.jetbrains.compose.resources.ExperimentalResourceApi

private const val MANIFEST_RESOURCE = "files/artist_images.json"
private const val BUCKET = "artist-images"

@Serializable private data class ArtistEntry(val file: String, val url: String? = null)

/**
 * Maps lineup artist display names to their image (public Supabase storage URL) and external
 * SoundCloud profile. The manifest is generated by `scripts/fetch_artist_images.py` and shipped as
 * a Compose resource — the client never re-derives slugs or hits the SoundCloud search API.
 */
class ArtistImages private constructor(private val byName: Map<String, ArtistEntry>) {
    fun urlFor(displayName: String): String? {
        val entry = byName[displayName] ?: return null
        return "${Config.SUPABASE_URL}/storage/v1/object/public/$BUCKET/${entry.file}"
    }

    fun soundcloudUrlFor(displayName: String): String? = byName[displayName]?.url

    companion object {
        val Empty: ArtistImages = ArtistImages(emptyMap())

        @OptIn(ExperimentalResourceApi::class)
        suspend fun load(): ArtistImages {
            val bytes =
                runCatching { Res.readBytes(MANIFEST_RESOURCE) }
                    .onFailure { logE("artist manifest missing: ${it.message}") }
                    .getOrNull() ?: return Empty
            // Tolerate unknown keys so adding fields to the manifest in the
            // future doesn't require a coordinated app release.
            val parser = Json { ignoreUnknownKeys = true }
            val map =
                runCatching {
                        parser.decodeFromString<Map<String, ArtistEntry>>(bytes.decodeToString())
                    }
                    .getOrElse {
                        logE("artist manifest parse failed: ${it.message}")
                        emptyMap()
                    }
            return ArtistImages(map)
        }
    }
}

/**
 * Provided by [App] once the manifest has been loaded. Defaults to an empty registry so previews
 * and tests don't blow up if the value isn't installed.
 */
val LocalArtistImages = staticCompositionLocalOf { ArtistImages.Empty }

private val ArtistSplitRegex = Regex("\\s+(?:b2b|f2f)\\s+", RegexOption.IGNORE_CASE)

/**
 * Split a set's artist string into its constituent performers.
 *
 * "Vortek's b2b Byorn" -> ["Vortek's", "Byorn"]. "Secret B2B" stays as-is (no surrounding
 * whitespace).
 */
fun splitArtists(setArtist: String): List<String> =
    ArtistSplitRegex.split(setArtist).map { it.trim() }.filter { it.isNotEmpty() }
